server:
  port: 80

face:
  job:
    base-path: imgs/face/job
    jar:
      filepath: C:\Users\wangxiaoming\.m2\repository\com\face\face-sdk\1.0-SNAPSHOT\face-sdk-1.0-SNAPSHOT.jar
      filename: face-sdk-1.0-SNAPSHOT.jar

  base-path: imgs/
