/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_face_sdk_jni_FaceSDK */

#ifndef _Included_com_face_sdk_jni_FaceSDK
#define _Included_com_face_sdk_jni_FaceSDK
#ifdef __cplusplus
extern "C" {
#endif
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_OK
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_OK 0L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_LICENSE_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_LICENSE_ERROR -1L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_IN_USER
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_IN_USER 201L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_ILLEGAL_PARAMETER
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_ILLEGAL_PARAMETER 300L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_FACE_SIZE_TOO_SMALL
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_FACE_SIZE_TOO_SMALL 301L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_UNKNOWN_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_UNKNOWN_ERROR 400L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_INIT_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_INIT_ERROR 401L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_EMPTY_MAT_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_EMPTY_MAT_ERROR 402L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_EMPTY_USER_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_EMPTY_USER_ERROR 403L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_FOUND_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_NOT_FOUND_ERROR 404L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_IO_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_IO_ERROR 405L
#undef com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_MODEL_LOAD_ERROR
#define com_face_sdk_jni_FaceSDK_FACE_SDK_STATUS_MODEL_LOAD_ERROR 405L
/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    faceModelInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_face_sdk_jni_FaceSDK_faceModelInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    faceModelConf
 * Signature: ([FI)I
 */
JNIEXPORT jint JNICALL Java_com_face_sdk_jni_FaceSDK_faceModelConf
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    faceDetect
 * Signature: ([BIILjava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_face_sdk_jni_FaceSDK_faceDetect___3BIILjava_util_ArrayList_2
  (JNIEnv *, jobject, jbyteArray, jint, jint, jobject);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    VideoCapture
 * Signature: ([C)J
 */
JNIEXPORT jlong JNICALL Java_com_face_sdk_jni_FaceSDK_VideoCapture___3C
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    VideoCapture
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_face_sdk_jni_FaceSDK_VideoCapture__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    releaseVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_face_sdk_jni_FaceSDK_releaseVideo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    isVideoOpened
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_sdk_jni_FaceSDK_isVideoOpened
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    read
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_face_sdk_jni_FaceSDK_read
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    faceDetect
 * Signature: (JLjava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_face_sdk_jni_FaceSDK_faceDetect__JLjava_util_ArrayList_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_face_sdk_jni_FaceSDK_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    writeMat
 * Signature: (J[C)Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_sdk_jni_FaceSDK_writeMat
  (JNIEnv *, jobject, jlong, jcharArray);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    showMat
 * Signature: ([CJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_sdk_jni_FaceSDK_showMat
  (JNIEnv *, jobject, jcharArray, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    rectangleMat
 * Signature: (JIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_sdk_jni_FaceSDK_rectangleMat
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    putTextMat
 * Signature: (J[CIIDDIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_sdk_jni_FaceSDK_putTextMat
  (JNIEnv *, jobject, jlong, jcharArray, jint, jint, jint, jdouble, jint, jint, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    cloneMat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_face_sdk_jni_FaceSDK_cloneMat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    releaseMat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_face_sdk_jni_FaceSDK_releaseMat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    waitKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_face_sdk_jni_FaceSDK_waitKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    showImg
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_face_sdk_jni_FaceSDK_showImg
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_face_sdk_jni_FaceSDK
 * Method:    createMat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_face_sdk_jni_FaceSDK_createMat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
